'use client';
import Sidebar from '../../components/sidebar';
import '../global.css';
import { Suspense } from 'react';
import { RecoilRoot } from 'recoil';

export const metadata = {
  title: 'Welcome to cs-admin',
  description: 'Generated by create-nx-workspace',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-screen h-screen overflow-hidden bg-[#F6FBFA] flex ">
      <div className="w-[20%]">
        <Suspense fallback="loading">
          <Sidebar name="adoakdo" avatar="awodao" />
        </Suspense>
      </div>
      <div className="overflow-y-scroll px-5 w-full">
        <Suspense fallback="loading">{children}</Suspense>
      </div>
    </div>
  );
}
