import { Open_Sans } from "next/font/google";

import "./global.css";

import Providers from "utils/providers";

export const metadata = {
  title: "Welcome to cs-admin",
  description: "Generated by create-nx-workspace",
  links: [
    {
      rel: "preload",
      as: "style",
      href: "/global.css",
    },
  ],
};

const openSans = Open_Sans({ subsets: ["latin"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
