'use client';
import './global.css';
import { RecoilRoot } from 'recoil';

export const metadata = {
  title: 'Welcome to cs-user',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body>{children}</body>
      </RecoilRoot>
    </html>
  );
}
